### PR TITLE
Build Project and Upload results to Github

### PR DESCRIPTION
**Pull request by MinimumDowntime**
GitHub Action to compile the solution on GitHub and upload build artifacts (Agent, Satellite, and Shared) to the current run that can be downloaded. ~~It _does not_ draft releases as there are several ways to go about that.~~

Runs on:
- On demand via GitHub Actions

Commented out a few sections around code signing. See the following screenshot for results of this Action.

build

### CODE REVIEW

**Comment by MinimumDowntime** [comment]
Moved back to draft. Looking to incorporate a release process.

**Comment by MinimumDowntime** [comment]
Updated action to support creating a Draft Release with associated Artifacts. The action now runs on demand, takes an input to write the tag/title for the drafted release.

**Comment by amadeo-alex** [comment]
Hello, finally I reached the stage of getting this done :D
I'll steal the config file to my dev repository and try to make required changes for the installer.
Then if you'll be so kind, I'll ping you to review them and make the same changes to your branch so we can merge it :)

**Comment by DrR0X-glitch** [comment]
Looks good to me, one thing you will want to be careful of @amadeo-alex is running actions on your own repo, in my experience I just disable them in my downstream one. You can definitely set it up correctly, just make sure you test it first :P

> No discord emoji :D

**Comment by amadeo-alex** [comment]
@MinimumDowntime could you please take a look an see if there's something that requires immediate attention?
I can already see how we can expand this in the future but for the basic releases it looks ok to me :D
Most likely tomorrow I'll merge it and test some 2.0.0beta release.

**Comment by MinimumDowntime** [comment]
Looks like you got it 👍

**Pull request merged**
