### PR TITLE
Fix: pressing escape while Alt-Tabbing (thus cancelling Alt-Tabbing) hiding Hass.Agent Window.

### PR DESCRIPTION
**Pull request by denisabt**
This fixing Issue #157

This is a PR to merge into main

### CODE REVIEW

**Comment by amadeo-alex** [comment]
Thank you for the fix :D
Would it possible to make it based on the https://github.com/hass-agent/HASS.Agent/tree/release-2.1.0?
I'll make a nice starter for 2.1.1 bugfix release!

I could in theory do it myself but I'd like to preserve your contribution :)

**Comment by denisabt** [comment]
Sure, makes absolutely sense, will do @amadeo-alex  ! :-)

**Comment by denisabt** [comment]
@amadeo-alex  - not sure I did that right :-> merge from/into main ? or do you prefer another source/target branch ?

**Comment by amadeo-alex** [comment]
First, sorry for the delay :D
Looks like there are still conflicts, let me fiddle with it and then comment again.

**Comment by amadeo-alex** [comment]
Ok, I changed the target to 2.1.1-beta2 that I plan to put out this weekend. With that the only change is the addition of one line in Main.cs - https://github.com/hass-agent/HASS.Agent/pull/161/files - does that look correct?

**Comment by denisabt** [comment]
@amadeo-alex - yes, that looks good, the fix was a really small code change - sounds bigger than actually was :-)  Thank you!

**Review by amadeo-alex — APPROVED** [review]
looks good

**Pull request merged**
