### PR TITLE
Feature: set audio input command

### PR DESCRIPTION
**Pull request by amadeo-alex**
This PR adds "SetAudioInputCommand" requested by Chrisdegod.
In current state both default audio input and default communications device is set.
Supports setting device configured within UI as well as sent as a payload on the command topic.

In addition, as a misc, this PR bumps beta version to "3".

db5Jxn

### CODE REVIEW

**Comment by DrR0X-glitch** [comment]
Here we go, here is my professional review of your C# or C++ code that you wrote.

It's good 😂

**Comment by hiagocosta** [comment]
tried with windows11 and change audio output, but the button that makes action of changing it is not working

**Comment by amadeo-alex** [comment]
> tried with windows11 and change audio output, but the button that makes action of changing it is not working. I'm in the new version (2.1.0-beta2)

was the 2.1.0-beta1 working fine for you?

**Comment by hiagocosta** [comment]
i've not tested...
is this feature wasn't available only in this new version?
I di'ndt notive that option on the lates version before the update, 

I will test and feedback you

**Pull request merged**
